//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddResourcessF.ShippingType {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddResourcessF.ShippingType.ResourceN", typeof(ResourceN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmDelete.
        /// </summary>
        public static string Are_you_sure_ {
            get {
                return ResourceManager.GetString("Are you sure?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableShippingType.
        /// </summary>
        public static string DataTableTitle {
            get {
                return ResourceManager.GetString("DataTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingFactor.
        /// </summary>
        public static string ShippingFactor {
            get {
                return ResourceManager.GetString("ShippingFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingNameA.
        /// </summary>
        public static string ShippingNameA {
            get {
                return ResourceManager.GetString("ShippingNameA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingNameE.
        /// </summary>
        public static string ShippingNameE {
            get {
                return ResourceManager.GetString("ShippingNameE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingType.
        /// </summary>
        public static string ShippingType {
            get {
                return ResourceManager.GetString("ShippingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LengthMenu.
        /// </summary>
        public static string Show_MENU_entries {
            get {
                return ResourceManager.GetString("Show MENU entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingNameA.
        /// </summary>
        public static string اسم_الشحنه {
            get {
                return ResourceManager.GetString("اسم الشحنه", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingNameE.
        /// </summary>
        public static string اشم_الشحنه {
            get {
                return ResourceManager.GetString("اشم الشحنه", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string البحث {
            get {
                return ResourceManager.GetString("البحث", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NextButton.
        /// </summary>
        public static string التالي {
            get {
                return ResourceManager.GetString("التالي", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجداول.
        /// </summary>
        public static string الجداول {
            get {
                return ResourceManager.GetString("الجداول", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreviousButton.
        /// </summary>
        public static string السابق {
            get {
                return ResourceManager.GetString("السابق", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string الوضع_التاثر {
            get {
                return ResourceManager.GetString("الوضع التاثر", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchPlaceholder.
        /// </summary>
        public static string بحث_ {
            get {
                return ResourceManager.GetString("بحث:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditButton.
        /// </summary>
        public static string تعديل {
            get {
                return ResourceManager.GetString("تعديل", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTableTitle.
        /// </summary>
        public static string جدول_امواع_الشحنه {
            get {
                return ResourceManager.GetString("جدول امواع الشحنه", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewButton.
        /// </summary>
        public static string جديد {
            get {
                return ResourceManager.GetString("جديد", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteButton.
        /// </summary>
        public static string حذف {
            get {
                return ResourceManager.GetString("حذف", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LengthMenu.
        /// </summary>
        public static string عرض_MENU_مدخلات {
            get {
                return ResourceManager.GetString("عرض MENU مدخلات", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfoText.
        /// </summary>
        public static string عرض_START_إلى_END_من_TOTAL_مدخلات {
            get {
                return ResourceManager.GetString("عرض START إلى END من TOTAL مدخلات", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingType.
        /// </summary>
        public static string نوع_الشحنه {
            get {
                return ResourceManager.GetString("نوع الشحنه", resourceCulture);
            }
        }
    }
}
