//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddResourcessF.EditShippingType {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddResourcessF.EditShippingType.EditA", typeof(EditA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string CancelButton1 {
            get {
                return ResourceManager.GetString("CancelButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عناصر النموذج الأساسية.
        /// </summary>
        public static string FormDescription {
            get {
                return ResourceManager.GetString("FormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عناصر النموذج الأساسية.
        /// </summary>
        public static string FormTitle_ {
            get {
                return ResourceManager.GetString("FormTitle ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلوب ادخال العدد من 5الي100.
        /// </summary>
        public static string LenghtName {
            get {
                return ResourceManager.GetString("LenghtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون معامل الشحن بين0.25و 100..
        /// </summary>
        public static string Range_ShippingFactor {
            get {
                return ResourceManager.GetString("Range_ShippingFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلوب إدخال معامل الشحن..
        /// </summary>
        public static string Required_ShippingFactor_ {
            get {
                return ResourceManager.GetString("Required_ShippingFactor ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلوب إدخال اسم نوع الشحن (بالعربيه)..
        /// </summary>
        public static string Required_ShippingTypeAname {
            get {
                return ResourceManager.GetString("Required_ShippingTypeAname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلوب إدخال اسم نوع الشحن (بالإنجليزية)..
        /// </summary>
        public static string Required_ShippingTypeEname {
            get {
                return ResourceManager.GetString("Required_ShippingTypeEname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معامل الشحن.
        /// </summary>
        public static string ShippingFactor {
            get {
                return ResourceManager.GetString("ShippingFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم نوع الشحن (بالعربية).
        /// </summary>
        public static string ShippingTypeAname {
            get {
                return ResourceManager.GetString("ShippingTypeAname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم نوع الشحن (بالإنجليزية).
        /// </summary>
        public static string ShippingTypeEname {
            get {
                return ResourceManager.GetString("ShippingTypeEname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        public static string SubmitButton {
            get {
                return ResourceManager.GetString("SubmitButton", resourceCulture);
            }
        }
    }
}
