//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddResourcessF.EditShippingType {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddResourcessF.EditShippingType.EditN", typeof(EditN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please to enter Lenght Value 5 To 100.
        /// </summary>
        public static string LenghtName {
            get {
                return ResourceManager.GetString("LenghtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Factor must be between 0.25and 100..
        /// </summary>
        public static string Range_ShippingFactor {
            get {
                return ResourceManager.GetString("Range_ShippingFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please to enter Shipping Type (Arabic).
        /// </summary>
        public static string Required_ShippingTypeAname {
            get {
                return ResourceManager.GetString("Required_ShippingTypeAname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please to enter Shipping Type (English).
        /// </summary>
        public static string Required_ShippingTypeEname {
            get {
                return ResourceManager.GetString("Required_ShippingTypeEname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required_ShippingFactor.
        /// </summary>
        public static string Shipping_Factor_is_required_ {
            get {
                return ResourceManager.GetString("Shipping Factor is required.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Factor.
        /// </summary>
        public static string ShippingFactor {
            get {
                return ResourceManager.GetString("ShippingFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingType.
        /// </summary>
        public static string ShippingType {
            get {
                return ResourceManager.GetString("ShippingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Type (Arabic).
        /// </summary>
        public static string ShippingTypeAname {
            get {
                return ResourceManager.GetString("ShippingTypeAname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Type (English).
        /// </summary>
        public static string ShippingTypeEname {
            get {
                return ResourceManager.GetString("ShippingTypeEname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitButton {
            get {
                return ResourceManager.GetString("SubmitButton", resourceCulture);
            }
        }
    }
}
