//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddResourcessF.Countrys {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Edit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Edit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddResourcessF.Countrys.Edit", typeof(Edit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryAname.
        /// </summary>
        public static string CountryAname {
            get {
                return ResourceManager.GetString("CountryAname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryEname.
        /// </summary>
        public static string CountryEname {
            get {
                return ResourceManager.GetString("CountryEname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countrys.
        /// </summary>
        public static string Countrys {
            get {
                return ResourceManager.GetString("Countrys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter CountryA Name .
        /// </summary>
        public static string EnterA {
            get {
                return ResourceManager.GetString("EnterA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter CountryE Name .
        /// </summary>
        public static string EnterE {
            get {
                return ResourceManager.GetString("EnterE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Length 10 TO 50.
        /// </summary>
        public static string LenghtName {
            get {
                return ResourceManager.GetString("LenghtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TabelCountrys.
        /// </summary>
        public static string TabelCountrys {
            get {
                return ResourceManager.GetString("TabelCountrys", resourceCulture);
            }
        }
    }
}
