//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddResourcessF.PaymentMethod {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PaymentMethodS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentMethodS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddResourcessF.PaymentMethod.PaymentMethodS", typeof(PaymentMethodS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cansel.
        /// </summary>
        public static string Cansel {
            get {
                return ResourceManager.GetString("Cansel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission .
        /// </summary>
        public static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please To Enter Commission Rqraured.
        /// </summary>
        public static string Commissions {
            get {
                return ResourceManager.GetString("Commissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teble Payment Method.
        /// </summary>
        public static string DataTableTitle {
            get {
                return ResourceManager.GetString("DataTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please to Enter Name Method Payment (Arbice).
        /// </summary>
        public static string EnterA {
            get {
                return ResourceManager.GetString("EnterA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please to Enter Name Method Payment (Engilsh).
        /// </summary>
        public static string EnterE {
            get {
                return ResourceManager.GetString("EnterE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please to Enter Length 3 mine TO 100.
        /// </summary>
        public static string LenghtName {
            get {
                return ResourceManager.GetString("LenghtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please to Enter (0.5).
        /// </summary>
        public static string LenghtNameCommissin {
            get {
                return ResourceManager.GetString("LenghtNameCommissin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method payment Arbice Name.
        /// </summary>
        public static string MethodAname {
            get {
                return ResourceManager.GetString("MethodAname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metyhod Payment Engilsh Name.
        /// </summary>
        public static string MethodEname {
            get {
                return ResourceManager.GetString("MethodEname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentMethod.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
    }
}
