//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddResourcessF.Settings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Seting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Seting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddResourcessF.Settings.Seting", typeof(Seting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cansel.
        /// </summary>
        public static string Cansel {
            get {
                return ResourceManager.GetString("Cansel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teble Siting .
        /// </summary>
        public static string DataTableTitle {
            get {
                return ResourceManager.GetString("DataTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KiloMeterRate.
        /// </summary>
        public static string KiloMeterRate {
            get {
                return ResourceManager.GetString("KiloMeterRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please To Enter Rote Kilo Metr.
        /// </summary>
        public static string KiloMeterRateVaildtion {
            get {
                return ResourceManager.GetString("KiloMeterRateVaildtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KilooGramRate.
        /// </summary>
        public static string KilooGramRate {
            get {
                return ResourceManager.GetString("KilooGramRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please To Enter Rote Klio Gream .
        /// </summary>
        public static string KilooGramRateVaildtion {
            get {
                return ResourceManager.GetString("KilooGramRateVaildtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please Enter Length Mine(0.5)Max(10000).
        /// </summary>
        public static string LenghtName {
            get {
                return ResourceManager.GetString("LenghtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seting.
        /// </summary>
        public static string Setings {
            get {
                return ResourceManager.GetString("Setings", resourceCulture);
            }
        }
        public static string RequiredFieldError
        {
            get
            {
                return ResourceManager.GetString("RequiredFieldError", resourceCulture);
            }
        }
        public static string LengthRequiredFieldError
        {
            get
            {
                return ResourceManager.GetString("LengthRequiredFieldError", resourceCulture);
            }
        }
        public static string EmailInvalidError
        {
            get
            {
                return ResourceManager.GetString("EmailInvalidError", resourceCulture);
            }
        }
        public static string PhoneNumberInvalidError
        {
            get
            {
                return ResourceManager.GetString("PhoneNumberInvalidError", resourceCulture);
            }
        }
        public static string PasswordLengthError
        {
            get
            {
                return ResourceManager.GetString("PasswordLengthError", resourceCulture);
            }
        }
        public static string ConfirmPasswordLengthErrors
        {
            get
            {
                return ResourceManager.GetString("ConfirmPasswordLengthErrors", resourceCulture);
            }
        }
        public static string PasswordMismatchError
        {
            get
            {
                return ResourceManager.GetString("PasswordMismatchError", resourceCulture);
            }
        }

    }

}
